language: php

sudo: false

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true
    include:
        - php: 7.1
          env: deps=low
        - php: 7.1
        - php: nightly
        - php: 7.2

before_script:
    - phpenv config-rm xdebug.ini || true
    - composer self-update
    - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest ; fi
    - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
    - vendor/bin/behat
