language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

php:
    - 7.2
    - 7.3
    - 7.4
    - nightly

before_install:
    - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install: travis_retry composer install

script:
    - vendor/bin/behat

jobs:
    allow_failures:
        - php: nightly

    include:
        - stage: Metrics and quality
          env: STATIC_ANALYSIS
          script:
              - ./vendor/bin/phpstan analyse

        - stage: Metrics and quality
          env: CODING_STANDARDS
          before_script:
              - wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
              - chmod a+x php-cs-fixer
          script:
              - ./php-cs-fixer fix --dry-run --stop-on-violation --using-cache=no

        - stage: Security Check
          env: SECURITY_CHECK
          before_script:
              - wget -c https://get.sensiolabs.org/security-checker.phar
              - chmod +x security-checker.phar
          script:
              - ./security-checker.phar security:check
